Make some ResourceUtils methods public
So that they are exposed for use in the swatch-core jar.

Otherwise we get errors like:

```
2021-07-23 17:32:15,016 [thread=http-nio-8080-exec-6] [ERROR] [org.candlepin.subscriptions.exception.mapper.BaseExceptionMapper] [Account: account123, Owner: org123]- SUBSCRIPTIONS1000: An internal server error has occurred. Check the server logs for further details.
java.lang.IllegalAccessError: class org.candlepin.subscriptions.resource.OptInResource tried to access method 'java.lang.String org.candlepin.subscriptions.resource.ResourceUtils.getAccountNumber()' (org.candlepin.subscriptions.resource.OptInResource is in unnamed module of loader org.springframework.boot.devtools.restart.classloader.RestartClassLoader @7e9d6a15; org.candlepin.subscriptions.resource.ResourceUtils is in unnamed module of loader 'app')
```